version: 1.0.{build}
max_jobs: 1
image: Visual Studio 2015
matrix:
  fast_finish: true
  allow_failures:
  - platform: x86
    configuration: Debug
  - platform: x64
    configuration: Debug
  - platform: x86
    configuration: Release
  - platform: x64
    configuration: Release

platform:
- Win32
- x64

configuration:
- Debug
- Release

cache:
- cmake-build/dependencies -> appveyor.yml, .gitmodules

install:
- powershell -Command "(gc .gitmodules) -replace 'git@github.com:', 'https://github.com/' | Out-File .gitmodules" -encoding UTF8
- git submodule update --init --recursive

before_build:
- if not exist cmake-build mkdir cmake-build
- cd cmake-build
- IF "%PLATFORM%"=="Win32" cmake -G "Visual Studio 14 2015" .. -DTEST_AHOY=ON
- IF "%PLATFORM%"=="x64" cmake -G "Visual Studio 14 2015 Win64" .. -DTEST_AHOY=ON

build:
  parallel: true
  project: cmake-build/ahoy.sln

after_build:
- for /R . %%f in (*.exe *.lib *.pdb *.dll) do copy %%f .
- for /F "delims=-" %%a in ("%APPVEYOR_REPO_BRANCH%") do set RELEASE=%%a
- 7z a ahoy-"%RELEASE%"-windows-"%CONFIGURATION%"-"%PLATFORM%".zip
  .\*.exe
  .\*.lib
  .\*.pdb
  .\*.dll

test_script:
- "%CONFIGURATION%\\ahoy-test.exe"

artifacts:
- path: cmake-build/*.zip
  name: built-zip

deploy:
  provider: GitHub
  auth_token:
    secure: VDOV/AdfTIABybc5t8uDDZHEAt9ug1oN5inrZvRNkj5bs1PoDeKFFXo2IoaXEc+r
  on:
    appveyor_repo_tag: true
  force_update: true
